### ISSUE TITLE
Segmentation fault when calling spiceweasel

### ISSUE THREAD

**Issue by scassiba** [mattray/spiceweasel#87]
I'm trying to use spiceweasel in conjunction with https://github.com/stackforge/openstack-chef-repo. When I call spiceweasel infrastructure.yml, I get a segmentation fault that suggests a bug in Ruby itself or some extension library. The full output is at https://gist.github.com/scassiba/9480e23cc52b858e6ab4

What I've done:
- gem pristine --all
- tried using ChefDK's embedded Ruby (that one fails in a different way -- https://gist.github.com/scassiba/d627e4938996c3a55cef)

I'm fully willing to blame my local environment for the segmentation fault, but the failure with ChefDK is probably worth a look as well.

**Comment by mattray** [comment]
I'll try to investigate this with the new 0.4.0 ChefDK

**Comment by mattray** [comment]
With the latest openstack-chef-repo, ChefDK 0.4.0 and system Ruby and clean gemsets with Ruby 2.1.5 and 2.2.0 I couldn't recreate this. Here's my output.

https://gist.github.com/mattray/4da8d9e9c1676aeec6ab

One thing I did notice is that I pinned Chef to 11, so I'll try upgrading to 12 to see how things work.

**Comment by scassiba** [comment]
I've surmised this to be something in my local environment. Completely wiping out my rvm install (thanks, rvm implode!) gets me back to a working state.

For some reason, rvm and ChefDK were coexisting peacefully for a while, then they weren't. I'll go ahead and close this since it's mostly a red herring, and can be worked around by just not using rvm.

**Comment by mattray** [comment]
@scassiba thanks for following up.
